# Backend (Laravel API)
server {
    listen 80;
    server_name api.devhub.pro www.api.devhub.pro www.api.devhub.com;

    return 301 http://api.devhub.com$request_uri;
}
server {
    listen 80;
    server_name api.devhub.com;

    location / {
        proxy_pass http://devhub_backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Frontend (React + Vite)
server {
    listen 80;
    server_name devhub.pro www.devhub.pro www.devhub.com;

    return 301 http://devhub.com$request_uri;
}
server {
    listen 80;
    server_name devhub.com;

    location / {
        proxy_pass http://devhub_frontend:5173;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
